[WIP] Add Footer section
CodeForAfrica/HURUmap-apps pull request #117
Opened 2019-01-22 10:58 UTC by nerdlet

## Description

Fixes #162380525

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Screenshots

![image](https://user-images.githubusercontent.com/3693563/51531130-ab7e3180-1e4d-11e9-9ecc-3fd1a7de741e.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2019-01-29 05:41 UTC, kilemensi requested changes

2019-01-29 05:41 UTC, kilemensi commented on dominion/frontend/src/assets/css/index.css
> +html {
We should try not to use general css files like this. All components should have styles defined in the components themselves.

2019-01-29 05:41 UTC, kilemensi commented on dominion/frontend/src/component/Footer/Partners.js
> +        </Grid>
This design works well for large screens but for small/extra small screens, the partners logos become to small and disappear completely.

![screenshot from 2019-01-29 08-11-55](https://user-images.githubusercontent.com/1779590/51886112-7028b900-239f-11e9-838f-a889c6358e0b.png)

2019-01-29 05:41 UTC, kilemensi commented on dominion/frontend/src/component/Footer/Partners.js
> +import PropTypes from 'prop-types';
Any reason Partners is part of Footer? Isn't it part of the page and hence should be its own component i.e. `src/components/Partners.js`

If it **is** part of Footer, then Footer should include Partners and pages should only include Footer i.e. Partners shouldn't be used outside the Footer.

2019-01-29 05:41 UTC, kilemensi commented on dominion/frontend/src/component/Footer/SocialMedia.js
> +import React from 'react';
Same as Partners. Either

 * Part of Footer: Then Footer should included it and **no other component/page** should know/use it, or
 * Component of its own: Move it to components folder ie. `src/components/SocialMedia.js`.

2019-01-29 05:41 UTC, kilemensi commented on dominion/frontend/src/component/Footer/index.js
> +  body: { color: '#f1f1ed', opacity: '0.6', paddingTop: '3rem' },
I think lets start from the get go using **_theme_** for these common styles.

2019-01-29 12:29 UTC, nerdlet commented on dominion/frontend/src/component/Footer/index.js
> +  body: { color: '#f1f1ed', opacity: '0.6', paddingTop: '3rem' },
@kilemensi Created a PR with the color palette and typography

2019-01-30 11:35 UTC, kilemensi requested changes
There is still issues on Small/Extra small screens:

They either look too big:

![screen shot 2019-01-30 at 14 31 20](https://user-images.githubusercontent.com/1779590/51978662-cbd86c80-249b-11e9-8244-2fa2b6ea08e2.png)

Or too small:

![screen shot 2019-01-30 at 14 31 32](https://user-images.githubusercontent.com/1779590/51978652-c2e79b00-249b-11e9-9ca2-61fd70fdbd78.png)

PS
---------------------------------------------------------

To include a component `components/Footer/index.js`, use:
```javascript
import Footer from '../component/Footer';
```
and not:

```javascript
import Footer from '../component/Footer/Index';`
```

2019-02-06 15:30 UTC, nerdlet commented
Hi @kilemensi Improved the images. This is how they look like presently

![image](https://user-images.githubusercontent.com/3693563/52352213-43c70980-2a3d-11e9-9f19-5d6b2347a9c6.png)

2019-02-07 05:09 UTC, kilemensi commented
> Hi @kilemensi Improved the images. This is how they look like presently
> 
> ![image](https://user-images.githubusercontent.com/3693563/52352213-43c70980-2a3d-11e9-9f19-5d6b2347a9c6.png)

Still look too big (see the iPad image)... But we'll sort it out when the page is complete.

2019-02-07 05:10 UTC, merged