[Dominion] Set up dominion hurumap-apps and react ui
CodeForAfrica/HURUmap-apps pull request #135
Opened 2019-02-21 15:31 UTC by KhadijaMahanga

## Description
This PR clean existing dominion hurumap-apps by removing frontend react app, adds the use of mapit on geojson, and creates django react ui for frontend.

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Screenshots

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2019-02-23 10:44 UTC, phillipahereza commented
@KhadijaMahanga could you move the `dominion_ui` app into the `dominion` app

2019-02-24 06:28 UTC, KhadijaMahanga commented
> @KhadijaMahanga could you move the `dominion_ui` app into the `dominion` app

@phillipahereza I have moved dominion_ui into dominon

2019-02-25 06:24 UTC, karimkawambwa commented on dominion/webpack.config.js
> +  //  new HWP({template: path.join(__dirname,'/dominion/templates/homepage.html')})
Minor nitpick, if we don't need it maybe just remove them all together.
Even from `package.json`.

2019-02-25 06:24 UTC, karimkawambwa commented on dominion/static/js/map_mapit.js
> +                   if (counter === 0) {
Minor nitpick maybe do the [decrement](https://github.com/CodeForAfrica/HURUmap-apps/pull/135/files#diff-28f11c7b5f6af8ab955cf76000148291R36) and check here so it not in many places when debugging.

2019-02-25 06:24 UTC, karimkawambwa commented on dominion/static/js/profile_map_mapit.js
> +var ProfileMaps = function() {
Maybe we should add a story to turn [these](https://github.com/CodeForAfrica/HURUmap-apps/pull/135/files#diff-28f11c7b5f6af8ab955cf76000148291R5) mapit js files into react components.

2019-02-25 06:24 UTC, karimkawambwa commented on dominion/settings.py
> +INSTALLED_APPS = ['dominion', 'dominion.dominion_ui'] + INSTALLED_APPS
Minor nitpick maybe lets rename `dominion_ui` to `frontend`.

2019-02-25 06:24 UTC, karimkawambwa commented on dominion/dominion_ui/tests.py
> +# -*- coding: utf-8 -*-
Empty files maybe just don't them it in here until we add logic.

- https://github.com/CodeForAfrica/HURUmap-apps/pull/135/files#diff-0edaf497805b6fd7f0b48727a7bd32bcR6
- https://github.com/CodeForAfrica/HURUmap-apps/pull/135/files#diff-a713d31f2e54514f01aa62cf4f910550R6
- https://github.com/CodeForAfrica/HURUmap-apps/pull/135/files#diff-f88e05aba4295cb63ba614c48f2a35bcR6

2019-02-25 06:48 UTC, kilemensi requested changes
Works @KhadijaMahanga, but it doesn't show the main thing we want to see: Multiple React components reacting in a single page. For example, how are we going to add a _React header_ at the top of the page and _React footer_ at bottom of the page while leaving everything in between to Django templates?

Basically, these choices outline in [React recommended Toolchain](https://reactjs.org/docs/create-a-new-react-app.html#recommended-toolchains):

    * If you’re learning React or creating a new single-page app, use Create React App.
    * If you’re building a server-rendered website with Node.js, try Next.js.
    * If you’re building a static content-oriented website, try Gatsby.
    * If you’re building a component library or integrating with an existing codebase, try More Flexible Toolchains.

I think we're on option 4 there.

------------------------------------------------

Other are just minor stuff like we use `yarn` and `yarn.lock` and not `package-lock.json`, `GPLv3`, etc.

2019-02-25 08:33 UTC, KhadijaMahanga commented
@karimkawambwa @kilemensi I have made requested changes. I have also updated a screenshot in the description

2019-02-25 09:28 UTC, phillipahereza approved these changes
@KhadijaMahanga LGTM

2019-02-25 10:24 UTC, karimkawambwa approved these changes
🚀

2019-02-26 06:07 UTC, closed without merging