[Dominion] Hero Component Review
CodeForAfrica/HURUmap-apps pull request #149
Opened 2019-03-05 10:26 UTC by KhadijaMahanga

## Description

Review and fix hero component for landing page

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots
![screenshot from 2019-02-28 18-28-24](https://user-images.githubusercontent.com/7962097/53798679-cdd59580-3f49-11e9-9db9-261b741c7c3f.png)

![screenshot from 2019-03-05 13-24-43](https://user-images.githubusercontent.com/7962097/53798902-3e7cb200-3f4a-11e9-8751-002775736b3f.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2019-03-05 13:05 UTC, kilemensi requested changes
@KhadijaMahanga:

 1. Map position is off:
![screenshot from 2019-03-05 15-37-54](https://user-images.githubusercontent.com/1779590/53807185-f8324d80-3f5f-11e9-8a06-db54208c401d.png)
 2. If you use `Select a country` to show country list, the header **countries** menu stays in closed state.
![screenshot from 2019-03-05 15-38-37](https://user-images.githubusercontent.com/1779590/53807288-3f204300-3f60-11e9-8f8e-6461f4ccc330.png)
 3. Mobile is broken.
![screenshot from 2019-03-05 15-38-11](https://user-images.githubusercontent.com/1779590/53807315-519a7c80-3f60-11e9-93f3-31e2a21d9896.png)
 4. Clicking countries list on mobile shows desktop countries list view instead of mobile countries list view.
![screenshot from 2019-03-05 15-38-21](https://user-images.githubusercontent.com/1779590/53807352-66771000-3f60-11e9-8bea-01e82ce4e1f0.png)

2019-03-05 13:05 UTC, kilemensi commented on dominion/dominion_ui/src/components/Header/Dropdown.js.rej
> +diff a/dominion/dominion_ui/src/components/Header/Dropdown.js b/dominion/dominion_ui/src/components/Header/Dropdown.js	(rejected hunks)
What is this file?

2019-03-05 13:48 UTC, KhadijaMahanga commented on dominion/dominion_ui/src/components/Header/Dropdown.js.rej
> +diff a/dominion/dominion_ui/src/components/Header/Dropdown.js b/dominion/dominion_ui/src/components/Header/Dropdown.js	(rejected hunks)
I have removed this

2019-03-06 09:55 UTC, karimkawambwa requested changes
Lets just resolve how we will merge our changes.

2019-03-06 09:55 UTC, karimkawambwa commented on dominion/templates/settings_js.html
> +  var dominion_countries = {{ HURUMAP.dominion_countries|jsonify|safe }};
I have this in country page as `SUPPORTED_COUNTRIES`

https://github.com/CodeForAfrica/HURUmap-apps/pull/149/files#diff-109a5726e848ca027ab25046be45eca9R12

https://github.com/CodeForAfrica/HURUmap-apps/pull/149/files#diff-eb52be4d0f274502984187e2ccda30aeR98

2019-03-06 09:55 UTC, karimkawambwa commented on dominion/settings.py
> +
I used @kilemensi  list of countries in country page.
I suggest we use that list, its merged in master.

2019-03-06 09:55 UTC, karimkawambwa commented on dominion/dominion_ui/src/components/Modal/GetLocation.js
> +            address => address.long_name === countryObj.name
Is this case insensitive ?

2019-03-06 09:55 UTC, karimkawambwa commented on dominion/dominion_ui/src/components/Modal/GetLocation.js
> +];
The urls will have to change to `/country-nam-slug` e.g. `/south-africa` so that they go to the country page.

2019-03-06 09:55 UTC, karimkawambwa commented on dominion/dominion_ui/src/components/Header/Dropdown.js
> +            <a href={`/profiles/${country.geoid}`} className={classes.link}>
url to change to `/country-name-slug`

2019-03-06 09:55 UTC, karimkawambwa commented on dominion/dominion_ui/src/components/Header/Dropdown.js
> +        )}
You could use the modal similar to how search bar is shown.

2019-03-06 12:47 UTC, KhadijaMahanga commented
@kilemensi I have fixed the requested changes

2019-03-06 15:13 UTC, kilemensi approved these changes
:+1: @KhadijaMahanga. Lets deploy this and close/finish `v0.1`

2019-03-06 15:13 UTC, karimkawambwa approved these changes

2019-03-06 15:21 UTC, merged