[Dominion][Bug] Fix map tiles and draw children level
CodeForAfrica/HURUmap-apps pull request #157
Opened 2019-03-11 12:45 UTC by KhadijaMahanga

## Description

`wmflabs tile` for map returns an ssl error on production. So we have switched to `openstreetmap` tile till we find a solution
 
Fixes # (issue)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2019-03-11 12:51 UTC, karimkawambwa approved these changes

2019-03-11 12:52 UTC, karimkawambwa commented on dominion/static/js/profile_map_mapit.js
> +        L.tileLayer('//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
😢

2019-03-11 14:23 UTC, KhadijaMahanga commented on dominion/static/js/profile_map_mapit.js
> +        L.tileLayer('//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
hah

2019-03-11 14:38 UTC, kilemensi requested changes
Visiting `tiles.wmflabs.org/bw-mapnik/` on Firefox, seems like their certificate is valid.
![Screenshot from 2019-03-11 17-31-18](https://user-images.githubusercontent.com/1779590/54131830-362de680-4424-11e9-8e8b-47ffaef3e83a.png)
 1. Include the exact error we're getting @KhadijaMahanga, here and/or on PT,
 2. Contact them to see if they're aware of it/it's a temporary situation/etc., and
 3. Include plan B in the PT.

2019-03-12 06:39 UTC, KhadijaMahanga commented
@kilemensi I updated the story. Yes, I see tiles.wmflabs.org/bw-mapnik/ is valid but its subdomain a.tiles.., b.tiles.., and c.titles.. are having that issues. Subdomains are used for parallel requests.

I have also tried to locate them but with no luck. I have included a plan B on the PT

2019-03-12 06:51 UTC, kilemensi commented
> @kilemensi I updated the story. Yes, I see tiles.wmflabs.org/bw-mapnik/ is valid but its subdomain a.tiles.., b.tiles.., and c.titles.. are having that issues. Subdomains are used for parallel requests.
> 
> I will ping OpenStreet. I have included a plan B on the PTMap

Lets look at https://leaflet-extras.github.io/leaflet-providers/preview/ and see if we can find something we can use e.g. `Esri.WorldGrayCanvas` seems to fit our need.

2019-03-13 05:08 UTC, KhadijaMahanga commented
@kilemensi `Esri.WorldGrayCanvas` looks good. But it has no multiple subdomains just as the `OpenStreetMap_BlackAndWhite`  Can we just stick with one domain for `OpenStreetMap_BlackAndWhite`?

2019-03-13 05:11 UTC, kilemensi commented
> @kilemensi `Esri.WorldGrayCanvas` looks good. But it has no multiple subdomains just as the `OpenStreetMap_BlackAndWhite` Can we just stick with one domain for `OpenStreetMap_BlackAndWhite`?

This is totally your call @KhadijaMahanga. I was merely pointing out that there are Gray/BW options out there for us to pick and choose instead of going back to the coloured OSM.

2019-03-13 13:08 UTC, kilemensi approved these changes

2019-03-13 18:23 UTC, merged