[Dominion] Video Modal
CodeForAfrica/HURUmap-apps pull request #159
Opened 2019-03-12 11:39 UTC by karimkawambwa

## Description

Update video modal look.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Screenshots

![Screen Shot 2019-03-12 at 2 38 39 PM](https://user-images.githubusercontent.com/4308339/54197280-93817080-44d4-11e9-9963-6232bbf2be63.png)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2019-03-13 09:15 UTC, nerdlet commented
@karimkawambwa Looks good to me. Maybe a heads up for later, used the same modal events for `How it Works` Component link to the video list...I'll create a story update the code on my end

2019-03-13 10:17 UTC, karimkawambwa commented
> Maybe a heads up for later

Will do pings on the dominion group but this change should not affect behaviour on your code, its none breaking but will definitely need update.

2019-03-13 12:56 UTC, kilemensi requested changes
@karimkawambwa:

 1. `Modal` component should encapsulate the `Navigation` logic. I see we're still moving `Navigation` around with the `Modal`. The only thing other components need to do is open and say what type of modal to open e.g. video, search, etc.,
 2. Scrollbars (especially horizontal ones) looks bad and should be removed,
![Screenshot from 2019-03-13 15-41-11](https://user-images.githubusercontent.com/1779590/54280010-82556400-45a7-11e9-901f-6d551eb8a93e.png)
 3. Mobile design needs improvement. It's quite difficult to tell the current video from playlist. I think playlist needs to be further down from current video and the thumbnails need to be _a wee bit smaller_ than the video (may be 75-85% of the screen width, but not 100%), and
![Screenshot from 2019-03-13 15-54-16](https://user-images.githubusercontent.com/1779590/54280344-4d95dc80-45a8-11e9-9b3c-3fdc341ba8fa.png)
 4. Clicking anywhere on the thumbnail should switch video (not just play button).

2019-03-13 12:56 UTC, kilemensi commented on dominion/dominion_ui/src/components/Video/Thumbnail.js
> +        backgroundImage: `url(https://img.youtube.com/vi/${videoId}/sddefault.jpg)`,
`sddefault` is not always available

2019-03-13 12:56 UTC, kilemensi commented on dominion/dominion_ui/src/components/Video/Player.js
> +              item
Only `<Grid container` or `<Grid item container` can contain `direction`, etc.
```
Warning: Failed prop type: The property `direction` of `Grid` must be used on `container`.
    in WithStyles(Grid) (at Player.js:82)
```

2019-03-14 07:48 UTC, karimkawambwa commented
> Modal component should encapsulate the Navigation logic. I see we're still moving Navigation around with the Modal. The only thing other components need to do is open and say what type of modal to open e.g. video, search, etc.,

Could i get some thoughts on the structure because at the moment in circles.
or could this be a different story ?

@KhadijaMahanga @nerdlet @kilemensi

2019-03-14 08:14 UTC, kilemensi commented
Create a chore story to track the Navigation/Modal implementaion and we'll deal with it at a later stage @karimkawambwa.

Just focus on the Video model on this PR.

  * Reduce the vertical space between Navigation and Video,
  * I think we should remove the scrolls altogether since they make our implementation a bit too different from the designs. Lets limit the maximum number of videos on the playlist... something between 4-6?,
  * The Player background has a bit of transparency, and
  * Playlist video titles are a bit harder to read on our implementation (increase size?).

Design

![Screenshot from 2019-03-14 11-08-47](https://user-images.githubusercontent.com/1779590/54340929-9487de80-4649-11e9-8021-c7c435ebdea1.png)

Current implementation

![Screenshot from 2019-03-14 11-09-34](https://user-images.githubusercontent.com/1779590/54340983-b84b2480-4649-11e9-887d-910e3bb5ee77.png)

2019-03-14 08:39 UTC, KhadijaMahanga requested changes
Also on titles, apart from increasing the font size..let's also change the font to `Lora` as per design

2019-03-14 10:54 UTC, karimkawambwa commented
@KhadijaMahanga @kilemensi 👀

2019-03-15 10:59 UTC, KhadijaMahanga approved these changes

2019-03-15 11:22 UTC, merged