Add country partner logo component
CodeForAfrica/HURUmap-apps pull request #160
Opened 2019-03-12 12:35 UTC by nerdlet

## Description

Fixes #164528283
## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

![image](https://user-images.githubusercontent.com/3693563/54200380-528d5a00-44dc-11e9-9093-81ec46c63fae.png)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2019-03-12 13:07 UTC, kilemensi requested changes
Looks good @nerdlet. Just a few code fixes

2019-03-12 13:07 UTC, kilemensi commented on dominion/dominion_ui/src/components/CountryPartners/PartnerContent.js
> +    </Grid>
Don't break `Grid` into separate components. This makes the component hard to reusable. This one should just use `div` i.e.
```jsx
<div>
  <Typography ....
    ...
  </Typography>
</div>
```

2019-03-12 13:07 UTC, kilemensi commented on dominion/dominion_ui/src/components/CountryPartners/index.js
> +      container
No need for `xs={12}` here, `<Grid container ...` is enough.

2019-03-12 13:07 UTC, kilemensi commented on dominion/dominion_ui/src/components/CountryPartners/index.js
> +    }
Mobile first design i.e. reverse the `theme.breakpoints.down` to `up`. e.g.
```javascript
logoGrid: {
  padding: '2rem', // Works for xs, sm and md
  [theme.breakpoints.up('lg')]: {
    padding: 0 // Or to whatever it should be for lg and xl screens
  }
}
```

2019-03-12 13:07 UTC, kilemensi commented on dominion/dominion_ui/src/components/CountryPartners/index.js
> +      <PartnerContent
Move the `Grid` layout from the component to here.

2019-03-12 13:07 UTC, kilemensi commented on dominion/dominion_ui/src/components/CountryPartners/index.js
> +      <Grid
`<Grid item`

2019-03-12 16:51 UTC, nerdlet commented
@kilemensi Updated the changes but kinda deleted some files that I need to add back. Will ping you when i've added them back

2019-03-12 18:13 UTC, nerdlet commented
@kilemensi Done

2019-03-13 04:39 UTC, kilemensi approved these changes

2019-03-13 04:39 UTC, merged