[Dominion] Profile Releases Section
CodeForAfrica/HURUmap-apps pull request #161
Opened 2019-03-13 11:36 UTC by karimkawambwa

## Description

Release section.

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

![Screen Shot 2019-03-13 at 2 35 59 PM](https://user-images.githubusercontent.com/4308339/54276059-5af99980-459d-11e9-86d9-9e1aba774bc4.png)
![Screen Shot 2019-03-13 at 2 35 41 PM](https://user-images.githubusercontent.com/4308339/54276061-5b923000-459d-11e9-85d8-376bc6fe9058.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2019-03-13 12:58 UTC, karimkawambwa commented
I have gone through the code but I am not sure what is the variable that holds the available releases. I can see releases setup in settings and and `profile_detail.html` has profileData variable has 

```
"primary_releases": {
		"active": {
			"citation": "Census, 2016",
			"name": "Census",
			"year": "2016"
		},
		"other": []
	}
```

Should i just show the active in the dropdown?
cc @KhadijaMahanga @kilemensi 




Full Json Below:
```{
	"demographics": {
		"total_population": {
			"index": {
				"this": null
			},
			"name": "People",
			"error_ratio": {
				"this": null
			},
			"values": {
				"this": 0
			},
			"numerators": {
				"this": 0,
				"district": 0,
				"province": 0,
				"country": 0
			},
			"error": {
				"this": 0
			},
			"numerator_errors": {
				"this": 0,
				"district": 0,
				"province": 0,
				"country": 0
			}
		},
		"is_missing": true
	},
	"primary_releases": {
		"active": {
			"citation": "Census, 2016",
			"name": "Census",
			"year": "2016"
		},
		"other": []
	},
	"geography": {
		"this": {
			"geo_code": "ZA",
			"child_level": "level1",
			"version": "2009",
			"short_name": "South Africa",
			"name": "South Africa",
			"full_name": "South Africa",
			"parent_geoid": "continent-AFR",
			"full_geoid": "country-ZA",
			"square_kms": 1221037.0,
			"geo_level": "country"
		},
		"parents": {
			"continent": {
				"geo_code": "AFR",
				"child_level": "country",
				"version": "2009",
				"short_name": "Africa",
				"name": "Africa",
				"full_name": "Africa",
				"parent_geoid": null,
				"full_geoid": "continent-AFR",
				"square_kms": null,
				"geo_level": "continent"
			}
		},
		"comparatives": []
	}
}```

2019-03-13 13:03 UTC, kilemensi commented
Yes @karimkawambwa, `primary_releases` is what you need. `active` is the one you show as selected/current and the dropdown should contain everything (`others` + `active`)

2019-03-13 13:25 UTC, karimkawambwa commented
The only thing left is getting metadata which i am not sure where I can get it. it seems wazimap has 
metadata 
```
profileData={
    "education": {
        "educational_attainment": {
            "percent_further_edu": {
                "values": {
                    "this": 32.0,
                    "country": 43.37
                },
                "name": "Completed Matric or higher",
                "index": {
                    "this": 100.0,
                    "country": 74.0
                },
                "error_ratio": {
                    "this": null,
                    "country": null
                },
                "error": {
                    "this": 0,
                    "country": 0
                },
                "numerator_errors": {
                    "this": 0,
                    "country": 0
                },
                "numerators": {
                    "this": 1199232,
                    "country": 14644033
                }
            },
            "percent_general_edu": {
                "values": {
                    "this": 64.66,
                    "country": 71.77
                },
                "name": "Completed Grade 9 or higher",
                "index": {
                    "this": 100.0,
                    "country": 90.0
                },
                "error_ratio": {
                    "this": null,
                    "country": null
                },
                "error": {
                    "this": 0,
                    "country": 0
                },
                "numerator_errors": {
                    "this": 0,
                    "country": 0
                },
                "numerators": {
                    "this": 2423458,
                    "country": 24232255
                }
            },
            "metadata": {
                "table_id": "HIGHESTEDUCATIONALLEVEL20",
                "release": "Community Survey 2016",
                "citation": "Statistics South Africa (2016) South African Community Survey 2016. Indicators derived from the full population Community Survey.",
                "universe": "Individuals 20 and older",
                "year": "2016"
            }
        },
```

2019-03-14 08:53 UTC, KhadijaMahanga requested changes
1. Dropdown position keeps changing. 

Here its on the right
![Screenshot from 2019-03-14 11-49-30](https://user-images.githubusercontent.com/7962097/54343239-702f0080-464f-11e9-93fe-a2a52bb7a5bd.png)

Here it covers the release dropdown
![Screenshot from 2019-03-14 11-49-57](https://user-images.githubusercontent.com/7962097/54343242-72915a80-464f-11e9-9c6f-5c32d266d189.png)

2. Active release is `Census`. But the template is still showing the Community Survey (still static)

3. The release dropdown icon is not changing on clicked (ArrowUp/ArrowDown)

2019-03-14 09:22 UTC, karimkawambwa commented
@kilemensi I am not sure what this means `Active release is Census. But the template is still showing the Community Survey (still static)`. I you mean the metadata, the citations then i actually don't now how to get these or where they are coming from. I will check with @KhadijaMahanga's  profile header.

2019-03-14 09:28 UTC, KhadijaMahanga commented
> @kilemensi I am not sure what this means `Active release is Census. But the template is still showing the Community Survey (still static)`. I you mean the metadata, the citations then i actually don't now how to get these or where they are coming from. I will check with @KhadijaMahanga's profile header.

@karimkawambwa I meant this variable
```
"primary_releases": {
		"active": {
			"citation": "Census, 2016",
			"name": "Census",
			"year": "2016"
		},
		"other": []
	}
```

Our active release is Census. So the release section should be describing census not community survey.

2019-03-14 11:02 UTC, karimkawambwa commented
> Our active release is Census. So the release section should be describing census not community survey.

@KhadijaMahanga thats why am not sure where to get that metadata, I am combing through code.
In wazimap i see this but i don't see it in hurumap ``` ,
            "metadata": {
                "table_id": "HIGHESTEDUCATIONALLEVEL20",
                "release": "Community Survey 2016",
                "citation": "Statistics South Africa (2016) South African Community Survey 2016. Indicators derived from the full population Community Survey.",
                "universe": "Individuals 20 and older",
                "year": "2016"
            }```

2019-03-14 11:47 UTC, karimkawambwa commented
@KhadijaMahanga 👀

2019-03-15 11:07 UTC, kilemensi commented on dominion/dominion_ui/src/components/ProfileReleases/index.js
> +    const Atag = ({ link }) => (
We have `A` component for links (it uses theme settings, etc.): https://github.com/CodeForAfrica/HURUmap-apps/blob/fe08690b233717f0fbc2f49d3888f0005db41bf8/dominion/dominion_ui/src/components/A.js#L9

2019-03-15 11:07 UTC, kilemensi commented on dominion/dominion_ui/src/components/ProfileReleases/index.js
> +  },
Again, why are you not using theme typography for `font` stuff?

2019-03-15 11:07 UTC, kilemensi commented on dominion/templates/profile/profile_detail.html
> +{% endblock %}
New line

2019-03-15 11:07 UTC, kilemensi commented on dominion/templates/profile/profile_detail.html
> +{% endblock %}
```javascript
        var current_dataset_release = profileData["primary_releases"]["active"];
        var dataset_releases = profileData["primary_releases"]["other"].concat(current_dataset_release);
```

This way, we don't mutate `profileData["primary_releases"]["other"]`.

2019-03-15 11:52 UTC, karimkawambwa commented on dominion/dominion_ui/src/components/ProfileReleases/index.js
> +  },
From the talk, we shall walk through to move thing to their appropriate theme.

2019-03-15 12:21 UTC, merged