[Dominion] Fixes - logo, map, footer on profile
CodeForAfrica/HURUmap-apps pull request #164
Opened 2019-03-18 12:35 UTC by KhadijaMahanga

## Description

Small fixes on logo link, add footer to profile page, and changed map tiles link

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2019-03-18 14:01 UTC, karimkawambwa approved these changes
looks good to me

2019-03-19 08:01 UTC, kilemensi requested changes
Few things @KhadijaMahanga:

 1. There is gap between footer and partners
![Screenshot from 2019-03-19 10-58-38](https://user-images.githubusercontent.com/1779590/54589273-481c1480-4a36-11e9-97ad-8a3659289919.png)
 2. There is a gap between hero and profiles tabs
![Screenshot from 2019-03-19 10-58-55](https://user-images.githubusercontent.com/1779590/54589293-536f4000-4a36-11e9-87ba-babda359160b.png)

2019-03-19 09:05 UTC, karimkawambwa requested changes
As soon as you start typing on the search, it appears broken.

![Screen Shot 2019-03-19 at 12 03 12 PM](https://user-images.githubusercontent.com/4308339/54593247-2ffcc300-4a3f-11e9-8793-23bcac2515a7.png)

2019-03-19 09:37 UTC, karimkawambwa commented on dominion/dominion_ui/public/index.html
>      </script>
Changes to allow yarn start

2019-03-19 14:53 UTC, KhadijaMahanga commented
@kilemensi pushed fixes

2019-03-19 14:54 UTC, KhadijaMahanga commented
> As soon as you start typing on the search, it appears broken.
> 
> ![Screen Shot 2019-03-19 at 12 03 12 PM](https://user-images.githubusercontent.com/4308339/54593247-2ffcc300-4a3f-11e9-8793-23bcac2515a7.png)

@karimkawambwa is this through `yarn start`?

2019-03-20 05:30 UTC, kilemensi approved these changes

2019-03-20 05:30 UTC, merged