[Dominion] Fix profile tabs hrefs + map zoom
CodeForAfrica/HURUmap-apps pull request #175
Opened 2019-03-28 14:37 UTC by KhadijaMahanga

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2019-03-29 09:16 UTC, karimkawambwa commented
> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

@KhadijaMahanga

2019-03-29 09:35 UTC, karimkawambwa reviewed
What sort of scroll behaviour are you going for ?
I don't see smooth scrolling and the tabs are hidden at the top when scrolling to profile section so you have to scroll all the way back.

2019-03-29 09:35 UTC, karimkawambwa commented on dominion/static/js/profile_map_mapit.js
> +      //  this.map.setView(this.dominion_country.centre, this.dominion_country.zoom);
remove this commented out code if its not useful anymore

2019-03-31 10:32 UTC, DavidLemayian requested changes
@KhadijaMahanga Please add description and screenshots.

2019-04-01 08:40 UTC, karimkawambwa approved these changes
From the description, works as intended 🚢 it.

2019-04-01 11:47 UTC, kilemensi approved these changes

2019-04-03 08:17 UTC, merged