[Nigeria] Add NBS data
CodeForAfrica/HURUmap-apps pull request #187
Opened 2019-06-24 09:51 UTC by KhadijaMahanga

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots
![Screenshot from 2019-06-24 12-49-28](https://user-images.githubusercontent.com/7962097/60009522-af251700-967e-11e9-8eca-b81566a122e3.png)
![Screenshot from 2019-06-24 12-48-47](https://user-images.githubusercontent.com/7962097/60009523-af251700-967e-11e9-8632-3d8380fe2268.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2019-06-26 05:57 UTC, kilemensi requested changes
Looks good @KhadijaMahanga... just a few SQL errors.

2019-06-26 05:57 UTC, kilemensi commented on hurumap_ng/sql/suspects_prosecuted.sql
> +country	NG	2016	2012	2194
Year `2012` repeated 5 times causing `could not create unique index "suspects_prosecuted_pkey"` error. You probably meant `2012, 2013, 2014, 2015, and 2016`

2019-06-26 05:57 UTC, kilemensi commented on hurumap_ng/sql/food_price.sql
> +ALTER TABLE IF EXISTS ONLY public.faac DROP CONSTRAINT IF EXISTS faac_pkey;
This this file is wrongly exported. It's talking about `faac` but it should be `food_price`.

2019-06-26 06:08 UTC, kilemensi commented
And just one general comment/question @KhadijaMahanga:

Why do we need **two** methods to fetch data for `2016` and `2018`? Aren't these just different release years of the same data?

2019-06-27 03:41 UTC, KhadijaMahanga commented
> And just one general comment/question @KhadijaMahanga:
> 
> Why do we need **two** methods to fetch data for `2016` and `2018`? Aren't these just different release years of the same data?

At the moment, there are of different tables for `2016` data and `2018`. Maybe as the data come in this will change. So I hid releases on front end  for now

2019-06-27 06:51 UTC, kilemensi commented
> At the moment, there are of different tables for `2016` data and `2018`. Maybe as the data come in this will change. So I hid releases on front end for now

Everybody is just hiding releases! What has releases ever done to anybody?

Cool but since everything comes from NBS, I think releases would have been perfect here.

2019-06-27 06:52 UTC, kilemensi approved these changes
:+1: @KhadijaMahanga

2019-06-27 06:52 UTC, merged