Add Human Development Profiles Instance
CodeForAfrica/HURUmap-apps pull request #49
Opened 2018-01-22 07:26 UTC by phillipahereza

## Description

Prototype for country HD profiles on HURUmap

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
![screencapture-localhost-8000-1516186640627](https://user-images.githubusercontent.com/13383422/35039300-7f336d26-fb8e-11e7-8a95-d1c03838e097.png)

![screencapture-localhost-8000-profiles-country-tza-tanzania-1516196843495](https://user-images.githubusercontent.com/13383422/35045831-2e27c612-fba6-11e7-9d9c-3c9ae28b238f.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2018-01-22 07:27 UTC, phillipahereza commented
@DavidLemayian I couldn't think of another way to remove the `league_table changed` (I honestly don't know how they got in there). Here is a clean PR

2018-01-22 16:33 UTC, DavidLemayian commented on humandevprofiles/settings.py
> +HUMANDEV = WAZIMAP
Let's only use `HURUMAP` for our purposes so that we don't have to overwrite some of the settings from `HURUMAP` that we'd use in templates.

2018-01-22 16:56 UTC, DavidLemayian requested changes
Requested changes on Slack.

2018-01-24 14:30 UTC, DavidLemayian commented
I'm not too happy with the placement of the static files but I'll merge for now and review this later.

2018-01-24 14:30 UTC, merged