Ft wajibisha template
CodeForAfrica/HURUmap-apps pull request #64
Opened 2018-05-16 11:18 UTC by phillipahereza

## Description

Update UI issues in Wajibisha

Fixes #56 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2018-05-16 13:31 UTC, DavidLemayian requested changes

2018-05-16 13:31 UTC, DavidLemayian commented on requirements-test.txt
> +whitenoise==3.3.1
@nerdlet Please delete this.

2018-05-18 06:59 UTC, yazminjumaali commented
Hi @nerdlet (cool name!) - team page needs names, roles and maybe link to Twitter? Also images are a distorted.

2018-05-18 09:51 UTC, phillipahereza commented
@nerdlet please update the team page screenshot

2018-05-18 13:23 UTC, phillipahereza commented
@nerdlet please fix, the cards aren't uniform
<img width="1256" alt="screen shot 2018-05-18 at 16 22 03" src="https://user-images.githubusercontent.com/13383422/40236937-b54e7044-5ab7-11e8-9619-d909bd05f66b.png">

<img width="1517" alt="screen shot 2018-05-18 at 16 17 42" src="https://user-images.githubusercontent.com/13383422/40236751-3a160234-5ab7-11e8-92f4-4229b913e672.png">

2018-05-18 14:05 UTC, DavidLemayian commented on requirements.txt
> +whitenoise==3.3.1
Do we need all of these?

2018-05-18 14:07 UTC, DavidLemayian commented on wajibisha/static/css/wajibisha.scss
> +.team.crard {
Is this correct?

2018-05-18 14:07 UTC, DavidLemayian commented on wajibisha/static/css/wajibisha.scss
> +btn-group.pl-4.pr-5.tab {
Is this correct?

2018-05-18 14:08 UTC, DavidLemayian commented on wajibisha/templates/_footer.html
> +            <a href="https://www.facebook.com/pesacheck"><i class="fa fa-facebook fa-lg fa-fw"></i></a>
Just confirming these aren't set in settings.

2018-05-18 14:11 UTC, DavidLemayian commented on wajibisha/templates/_footer.html
> +        <p class="">
Empty class needs fix.

2018-05-18 14:12 UTC, DavidLemayian commented on wajibisha/templates/about.html
>  </div>
This about page looks like it's a copy of what is on Medium. Should we not point to that instead if nothing different?

2018-05-22 14:01 UTC, merged