HURUmap Zimbabwe
CodeForAfrica/HURUmap-apps pull request #73
Opened 2018-06-12 07:33 UTC by phillipahereza

## Description

Create a HURUmap instance for Zimbabwe

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Screenshots
![screencapture-localhost-8000-2018-06-12-10_30_24](https://user-images.githubusercontent.com/13383422/41276109-ce860874-6e2b-11e8-8913-b08f890529c5.png)
![screencapture-localhost-8000-profiles-district-1805-masvingo-2018-06-12-10_30_03](https://user-images.githubusercontent.com/13383422/41276110-cec759dc-6e2b-11e8-8456-514ebf9489d6.png)
![screencapture-localhost-8000-profiles-province-18-masvingo-2018-06-12-10_29_41](https://user-images.githubusercontent.com/13383422/41276111-cf02aa50-6e2b-11e8-9537-e6712f4c9484.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

2018-08-16 12:22 UTC, kilemensi commented
To confirm @phillipahereza , this is just a map with:
 

- country and provinces
- no regions, districts or wards
- no census data

2018-08-16 12:23 UTC, phillipahereza commented
@kilemensi yes, but don't merge as yet

2018-08-16 12:24 UTC, kilemensi commented
Alright @phillipahereza , can I assign it back to you so I know it's not waiting on me?

2018-08-23 11:08 UTC, DavidLemayian commented
@kilemensi + @phillipahereza perhaps to make it easier to know it's WIP please add `[WIP]` at the beginning of the title?

2018-10-03 05:59 UTC, phillipahereza commented
@kilemensi please review

2018-10-03 15:26 UTC, kilemensi requested changes

2018-10-03 15:26 UTC, kilemensi commented on hurumap_zw/settings.py
> +    },
I see `geo/ward.topojson` below, shouldn't ward also be a level here?

2018-10-03 15:26 UTC, kilemensi commented on hurumap_zw/settings.py
> +}
Do not replace the whole `DATABASES` object, replace only the part we need. i.e.
```python
DATABASES['default'] = dj_database_url.parse( ...
```

2018-10-03 15:27 UTC, kilemensi commented
PS: Lets create and add Google Analytics id for Zimbabwe as well @phillipahereza .

2018-10-03 19:10 UTC, phillipahereza commented on hurumap_zw/settings.py
> +    },
@kilemensi I removed it for now, the data he gave me doesn't go that far down, I could easily add them back if needed

2018-10-04 04:55 UTC, kilemensi approved these changes

2018-10-04 04:56 UTC, merged