[Feature] HURUmap-Apps:Land Implement "Discover" banner as floating box
CodeForAfrica/HURUmap-apps pull request #95
Opened 2018-10-25 09:22 UTC by KhadijaMahanga

## Description

Discover banner as floating box on landing page (top of the map)

Fixes  [story](https://www.pivotaltracker.com/story/show/161441285)
## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Screenshots
![47856641-bd28dd80-ddf8-11e8-8875-ddb4bbe6591f](https://user-images.githubusercontent.com/7962097/47904830-b0f35d80-de96-11e8-88ba-6acec51b28b7.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2018-10-25 11:24 UTC, DavidLemayian requested changes
Let's make the three changes:
1. The `<hr>` to be the light green
2. Button should be solid light green colour
3. Make the X button gray

2018-10-25 11:25 UTC, DavidLemayian requested changes
Also add slight offset shadow to the box.

2018-10-25 11:27 UTC, DavidLemayian requested changes

2018-10-25 11:27 UTC, DavidLemayian commented on hurumap_land/templates/homepage.html
> +  </style>
Also move this to hurumap_land.scss with more appropriate class names + heirachy. e.g `.map-explainer` and `.map-explainer button` to avoid conflict for other `button` elements.

2018-10-25 11:28 UTC, DavidLemayian commented on hurumap_land/templates/homepage.html
> +{% block header_content %}{% endblock header_content %}
Please add comment here on what's happening.

2018-10-27 12:07 UTC, KhadijaMahanga commented
@DavidLemayian I have push requested changes on branch/PR

![screenshot from 2018-10-27 15-04-00](https://user-images.githubusercontent.com/7962097/47603839-faa4f980-d9f9-11e8-9ac9-5e06d9b64911.png)

2018-10-27 12:25 UTC, KhadijaMahanga commented on hurumap_land/templates/homepage.html
> +{% block header_content %}{% endblock header_content %}
@DavidLemayian the block `header_content` includes the discover stories component that sits on top of the map. So I removed html elements in that block, and passed empty content so that it should not show in our new design. 

And because the floating box is on top of the map which is housed by the `content_container` block. I had to introduce `content_container` and perform customization by adding the floating box.  `how it works`, `showcases` and `partners` also live in the block `content_container`. As per HURUmap homepage layout

2018-10-31 06:54 UTC, DavidLemayian commented on hurumap_land/templates/homepage.html
> +{% block header_content %}{% endblock header_content %}
@KhadijaMahanga Yip, I figured as much.

The in-line/in-code comment is for future devs to understand the same thing quickly too.

2018-11-01 14:08 UTC, KhadijaMahanga commented
@DavidLemayian updated screenshot
![screenshot from 2018-11-01 17-03-13](https://user-images.githubusercontent.com/7962097/47856641-bd28dd80-ddf8-11e8-8875-ddb4bbe6591f.png)

2018-11-10 21:00 UTC, DavidLemayian approved these changes

2018-11-10 21:00 UTC, merged